# Exercícios - Aula 2

In [10]:
import numpy as np

In [84]:
# Crie uma lista com os valores 2,4,6,8,10. Chame a lista de "valores"
# Escreva seu código Abaixo:

idades = [2,4,6,8,10]

In [85]:
idades

[2, 4, 6, 8, 10]

In [93]:
# Use funções do Numpy para extrair as seguintes informações da lista:

media=np.mean(idades)
media

np.float64(6.0)

In [87]:
# Mínimo - chame o resultado de minimo:

minimo = np.min(idades)
minimo

np.int64(2)

In [88]:
# Soma - chame o resultado de soma:
soma = np.sum(idades)
soma

np.int64(30)

In [89]:
# Máximo - chame o resultado de maximo:
maximo = np.max(idades)
maximo

np.int64(10)

In [94]:
# Checando a resposta:

if soma == 30:
    print('soma - Correto')
else:
    print('soma - Tente Novamente')
    
    
# Checando a resposta:

if media == 6:
    print('media - Correto')
else:
    print('media - Tente Novamente')
    
    
# Checando a resposta:

if minimo == 2:
    print('minimo - Correto')
else:
    print('minimo - Tente Novamente')
    
    
# Checando a resposta:

if maximo == 10:
    print('maximo - Correto')
else:
    print('maximo - Tente Novamente')

soma - Correto
media - Correto
minimo - Correto
maximo - Correto

In [95]:
# Qual o método do Pandas usado para importar dados?
# Digite sua resposta abaixo:

var = pd.read_csv

In [32]:
import pandas as pd

# O método pd.DataFrame() pode ser usado para criar um DataFrame vazio

lista1 = ['a','b','c','d']
lista2 = [1,2,3,4]

df = pd.DataFrame()

df['Col1'] = lista1
df['Col2'] = lista2

df

  Col1  Col2
0    a     1
1    b     2
2    c     3
3    d     4

In [38]:
# Considere o Dataframe df gerado acima

# Use o método head para retornar as 2 primeiras linhas:


df.head(2)

  Col1  Col2
0    a     1
1    b     2

In [39]:
# Use o método count() para retornar a quantidade de registros no DataFrame


df.count()

Col1    4
Col2    4
dtype: int64

In [40]:
# Use o método describe para retornar as estatísticas descritivas do DataFrame

df.describe()

           Col2
count  4.000000
mean   2.500000
std    1.290994
min    1.000000
25%    1.750000
50%    2.500000
75%    3.250000
max    4.000000

In [58]:
# Crie uma lista com 4 valores [10,20,30,40] e chame de lista3
# Adicione uma coluna nova no Dataframe df com os valores da lista3:

lista3 = [10,20,30,40]
df["novaColuna"] = lista3
print(df)

  Col1  Col2  novaColuna
0    a     1          10
1    b     2          20
2    c     3          30
3    d     4          40

In [56]:
df = df.drop(columns=["Nova_Coluna"])

In [57]:
# Imprima os tipos de variável de todas as colunas do DataFrame:

df.dtypes

Col1          object
Col2           int64
novaColuna     int64
dtype: object

In [59]:
import pandas as pd

df2 = pd.DataFrame()

lista4 = ['a','b','c','d','e']
lista5 = [3,5,7,9,11]
lista6 = [30,50,70,90,110]

df2['Col1'] = lista4
df2['Col5'] = lista5
df2['Col6'] = lista6

df2

  Col1  Col5  Col6
0    a     3    30
1    b     5    50
2    c     7    70
3    d     9    90
4    e    11   110

In [72]:
# Faça o cruzamento dos dois dataframes, df e df2

# Descubra qual coluna será usada como chave de cruzamento, e faça o cruzamento usando o método pd.merge
coluna = list(set(df.columns) & set(df2.columns))[0] 
print(coluna)
# Use Left Join, chame o dataframe resultante de df3:

# Analise a diferença entre os dois dataframes

Col1

In [73]:
# Descubra qual coluna será usada como chave de cruzamento, e faça o cruzamento usando o método pd.merge
df3 = pd.merge(df, df2, on="Col1", how="inner")

print(df3)

  Col1  Col2  Col5  Col6
0    a     1     3    30
1    b     2     5    50
2    c     3     7    70
3    d     4     9    90

In [103]:
# Use Right Join, chame o dataframe resultante de df4:
df4 = pd.merge(df, df2, on="Col1", how="right")

print(df4)

  Col1  Col2  Col5  Col6
0    a   1.0     3    30
1    b   2.0     5    50
2    c   3.0     7    70
3    d   4.0     9    90
4    e   NaN    11   110