# Aula 2 - Começando a manipulação de Dados

## Numpy

In [2]:
import numpy as np

In [ ]:
!pip install numpy

In [ ]:
idades = [30,5,10,7]

In [ ]:
idades

In [ ]:
# min = Mínimo

np.min(idades)

In [ ]:
# max = Máximo

np.max(idades)

In [ ]:
#mean = média

np.mean(idades)

In [ ]:
#std = Desvio Padrão

np.std(idades)

In [ ]:
# sum = Soma

np.sum(idades)

In [ ]:
# isnan - Retorna True quando o valor é vazio
# nan - Retorna um valor vazio

idades[1]

In [ ]:
np.nan

In [ ]:
idades.append(np.nan)
idades

In [ ]:
np.isnan(idades[4])

In [ ]:
idades.remove(np.nan)

In [ ]:
# Quantile - Retornar Quantil da sua série de dados



np.quantile(idades,0.75)

In [ ]:
idades

## Pandas

In [5]:
import pandas as pd

In [7]:
base = pd.read_csv(r'C:\Users\Aluno\Desktop\phyton-juliana\Aula 2\train.csv')

In [8]:
base.to_csv(r'C:\Users\Aluno\Desktop\phyton-juliana\Aula 2\train_exportado.csv')

In [ ]:
#base criada por fora em excel
base

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833.00,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925.00,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,300.00,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
#titulo das colunas
base.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833.00,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925.00,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,300.00,NaN,S

In [ ]:
#tudo que pode ser somado (números)
base.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,8.910000e+02
mean,446.000000,0.383838,2.308642,29.717325,0.523008,0.381594,7.424598e+05
std,257.353842,0.486592,0.836071,14.591695,1.102743,0.806057,5.995953e+06
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000e+00
25%,223.500000,0.000000,2.000000,20.000000,0.000000,0.000000,2.655000e+01
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,7.333000e+03
75%,668.500000,1.000000,3.000000,38.750000,1.000000,0.000000,2.546670e+05
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,1.240913e+08

In [ ]:
#soma da quantidade de registros para cada coluna da tabela
base.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [14]:
base.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [16]:
base.mean()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

## Métodos usados para manipulação de DataFrames

In [17]:
# Head - Visualizar primeiras linhas da tabela

base.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833.00,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925.00,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,300.00,NaN,S

In [18]:
# Count - Contar registros na base

base.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [19]:
# Describe - Visão geral da base

base.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,8.910000e+02
mean,446.000000,0.383838,2.308642,29.717325,0.523008,0.381594,7.424598e+05
std,257.353842,0.486592,0.836071,14.591695,1.102743,0.806057,5.995953e+06
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000e+00
25%,223.500000,0.000000,2.000000,20.000000,0.000000,0.000000,2.655000e+01
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,7.333000e+03
75%,668.500000,1.000000,3.000000,38.750000,1.000000,0.000000,2.546670e+05
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,1.240913e+08

In [20]:
base['PassengerId']

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64

In [21]:
base[['PassengerId','Survived','Age']].mean()

PassengerId    446.000000
Survived         0.383838
Age             29.717325
dtype: float64

In [22]:
# Saber o tipo de variável de cada coluna do dataframe

base.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [23]:
type(base['Ticket'][1])

str

## Segmentação de Dataframes

### Loc e Iloc

In [3]:
base

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
# Não segue a regra geral : Primeiro número incluso e último número também está incluso
# Porque estamos chamando rótulos, e não números

base.loc[0:5,['PassengerId','Pclass']]

   PassengerId  Pclass
0            1       3
1            2       1
2            3       3
3            4       1
4            5       3
5            6       3

In [13]:
# Segue a regra geral: Primeiro número incluso, e último número não incluso
# Porque estamos chamando índices/números e não rótulos

base.iloc[-4:,-3:]

      Fare Cabin Embarked
887  30.00   B42        S
888  23.45   NaN        S
889  30.00  C148        C
890   7.75   NaN        Q

In [31]:
base[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833.00,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925.00,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,300.00,NaN,S

In [32]:
base['PassengerId']

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64

In [33]:
base[['PassengerId','Survived']]

     PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]

In [34]:
base[base['Survived'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833.0000,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925.0000,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,300708.0000,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7225.0000,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,831583.0000,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [18]:
# Criar uma coluna Nova

base['ColunaNova'] = pd.Series()
base['ColunaNova2'] = base['PassengerId'] + base['Survived']

In [35]:
base

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833.00,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925.00,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,300.00,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### Merge

In [36]:
base

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,712833.00,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7925.00,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,300.00,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [37]:
base2 = base[['PassengerId','Survived','Name']]
base3 = base[['PassengerId','Sex','Age']]

In [22]:
base2

     PassengerId  Survived                                               Name
0              1         0                            Braund, Mr. Owen Harris
1              2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2              3         1                             Heikkinen, Miss. Laina
3              4         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              5         0                           Allen, Mr. William Henry
..           ...       ...                                                ...
886          887         0                              Montvila, Rev. Juozas
887          888         1                       Graham, Miss. Margaret Edith
888          889         0           Johnston, Miss. Catherine Helen "Carrie"
889          890         1                              Behr, Mr. Karl Howell
890          891         0                                Dooley, Mr. Patrick

[891 rows x 3 columns]

In [38]:
base3

     PassengerId     Sex   Age
0              1    male  22.0
1              2  female  38.0
2              3  female  26.0
3              4  female  35.0
4              5    male  35.0
..           ...     ...   ...
886          887    male  27.0
887          888  female  19.0
888          889  female   NaN
889          890    male  26.0
890          891    male  32.0

[891 rows x 3 columns]

In [41]:
base4 = pd.merge(base2,base3, on = 'PassengerId', how = 'left')

In [40]:
base4

,PassengerId,Survived,Name,Sex,Age
0,1,0,"Braund, Mr. Owen Harris",male,22.0
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
2,3,1,"Heikkinen, Miss. Laina",female,26.0
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,5,0,"Allen, Mr. William Henry",male,35.0
...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",male,27.0
887,888,1,"Graham, Miss. Margaret Edith",female,19.0
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN
889,890,1,"Behr, Mr. Karl Howell",male,26.0
890,891,0,"Dooley, Mr. Patrick",male,32.0

In [42]:
base4.to_excel(r'C:\\Users\Aluno\Desktop\phyton-juliana\Aula 2\base4.xlsx')